version: '3'

services:
  wise-api:
    container_name: wise-api
    hostname: wise-api
    image: wise-api:latest
    build:
      context: ./wise-api
      dockerfile: Dockerfile
    ports:
      - "8020:8080"
  wise-ui:
    container_name: wise-ui
    image: wise-ui:latest
    build:
      context: ./wise-ui
      dockerfile: Dockerfile
    depends_on:
      - wise-api
    ports:
      - "8021:80"
